all:
  children:
    database:
      hosts:
        staging-db:
          ansible_host: 192.168.100.10
    monitoring:
      hosts:
        staging-monitor:
          ansible_host: 192.168.100.20
    rust:
      hosts:
        staging-api:
          ansible_host: 192.168.100.30
