postgres_version: "15"
postgres_user: "admin"
postgres_password: "password"
postgres_main_db: "auth"
postgres_extra_dbs:
  - "data"
  - "device"
postgres_port: "5432"
postgres_docker_image: "postgres:{{ postgres_version }}"
postgres_docker_volume: "pgdata"
