- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present
  become: true

- name: Ensure PostgreSQL is started and enabled
  service:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Configure PostgreSQL to listen on all interfaces
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '{{ postgres_listen_addresses }}'"
  notify: Restart PostgreSQL
  become: true

- name: Allow connections from any host
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    insertafter: EOF
    line: "host all all 0.0.0.0/0 md5"
  notify: Restart PostgreSQL
  become: true

- name: Set PostgreSQL password
  become_user: postgres
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    role_attr_flags: "LOGIN"

- name: Create PostgreSQL databases
  become_user: postgres
  postgresql_db:
    name: "{{ item }}"
    owner: "{{ postgres_user }}"
  loop: "{{ postgres_databases }}"
