- hosts: all
  become: true
  roles:
    - docker_setup

- hosts: database
  become: true
  roles:
    - postgres

- hosts: monitoring
  become: true
  roles:
    - prometheus
    - grafana
    - loki
