- name: Setup docker
  hosts: all
  become: true
  roles:
    - docker_setup
    - node_exporter
    - postgres
    - prometheus
    - grafana
    - loki

- name: Setup greenhouse services
  hosts: all
  become: true
  roles:
    - greenhouse_input_alert_trigger
    - greenhouse_input_output_saver
    - greenhouse_periodic_alert

- name: Setup OpenGreenhouseManager application
  hosts: opengreenhousemanager
  become: true
  roles:
    - opengreenhousemanager
